TOPDIR ?= ../..
include $(TOPDIR)/.config

$(TWITTER_BOT_SUPPORT)_SRC += services/twitter_bot/twitter_bot.c

##############################################################################
# generic fluff
include $(TOPDIR)/scripts/rules.mk
